### PR TITLE
Fix PHP 7.4 deprecation warnings

### PR DESCRIPTION
**Pull request by HLeithner**
Fix for issue #5 

Change curly braces to square brackets.

### CODE REVIEW

**Comment by brianteeman** [comment]
Any chance this can get merged?

**Comment by emielmolenaar** [comment]
A merge would be awesome!

**Comment by wamania** [comment]
sorry guys, haven't see it
merged

**Comment by HLeithner** [comment]
Thanks

**Comment by emielmolenaar** [comment]
Thank you!

**Pull request merged**
