### PR TITLE
Add an interface to abstract the public API

### PR DESCRIPTION
**Pull request by lcobucci**
I couldn't hold myself and also did some other small improvements on the lib.

### CODE REVIEW

**Comment by wamania** [comment]
Thanks for your improvements, i agree with them all.

**Comment by lcobucci** [comment]
@wamania nice, thanks!

**Comment by lcobucci** [comment]
@wamania btw do you have a roadmap for this lib? I mean, what are your plans in terms of updating and improving it?

**Comment by wamania** [comment]
I will finish Russian and Finnish (probably this month), no plan after that.

**Comment by lcobucci** [comment]
@wamania I see, I was wondering if you were interested in:

- updating it to PHP 7+ (or at least PHP 5.6)
- adding custom exceptions
- maybe some other small improvements (reduce cyclomatic complexity, improve the interfaces, add unit tests, etc)

**Comment by wamania** [comment]
I'm working on configure travis to launch test, i will pass to php 5.6+ (current version on debian8, my reference)
Custom exceptions, it would be nice.
I don't think there is a need for reducing cyclomatic complexity, it's quite simple. I think current tests are enough. May be i should add a factory to build instance, i think about it.

But no roadmap ;)

**Pull request merged**
