### PR TITLE
Removing dependency on voku/portable-utf8

### PR DESCRIPTION
**Pull request by Hackwar**
Unfortunately it seems as of voku/portable-utf8 has been abandoned. This PR switches the dependency to joomla/string, which provides basically the same functionality and is one megabyte less code... It also raises the system requirements to php 8.1.

### CODE REVIEW

**Comment by wamania** [comment]
Hi Hackware, 

Thx for this update, i ran the tests and it seems ok since php7.3
In the composer.json you don't raise to 8.1 neither in the github workflow

So, 7.3 or 8.1 ?

**Comment by Hackwar** [comment]
@HLeithner requested me to use version 2 of the Joomla package, which is still compatible with 7.2, so I chose that and did not require the raised requirements.

**Comment by Hackwar** [comment]
I'm not entirely sure if the version limitation is correct the way it is, since it should also allow higher versions of the Joomla package. For Joomla to use it itself, we would have to be allowed to use version 3 as well.

**Comment by Hackwar** [comment]
@wamania Any news on this? :-) We at Joomla would like to drop that library soon..ish and depend a little bit on a decision here.

**Comment by Hackwar** [comment]
Thank you!

**Pull request merged**
